language: ruby
rvm:
  - 2.2.2
  - jruby-1.7.19
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: 2.2.2
      jdk: oraclejdk7
    - rvm: 2.2.2
      jdk: oraclejdk8
sudo: false
cache: bundler
deploy:
  provider: rubygems
  api_key:
    secure: bdKrctjfSWJ5bhPOVL2Amr2/hbCa6J0QGhIsl7ZbWSitSP17sW8wN8E2TSECGHAouymzZ9SmFKCJpTrjpdd6lA3ATHoMcRl2c5qHVcL0IyZ1Q89sVxnhCt/nXzoCOG1FzLyyHfiGq4/RbB3e04xG2ZWPkuLZMGJnFqChNciNPB0=
  gem: duse
  on:
    tags: true
    repo: duse-io/duse.rb
